production:
  scrape_watches_morning:
    class: ScrapeWatchesJob
    queue: default
    schedule: at 2am every day
  scrape_watches_noon:
    class: ScrapeWatchesJob
    queue: default
    schedule: at 11:45am CT every day

development:
  scrape_watches:
    class: ScrapeWatchesJob
    queue: default
    schedule: every 30 minutes
